### ISSUE TITLE
Colors Invert when screen refreshes

### ISSUE THREAD

**Issue by maclobdell** [cypresssemiconductorco/mbed-os-example-emwin-eink#1]
I am using this example as a reference for another project.  I haven't changed much other than the text on the display.

I noticed that when the screen is refreshed, the colors invert.  This is not pleasant.  Is there a workaround for this? 

I have uploaded pictures to explain the issue.

I start with this screen.
![screen1](https://user-images.githubusercontent.com/6129601/71794678-38db7700-3008-11ea-8a31-1cdc3287a443.PNG)

Then I want to transition to the next, but first the colors invert.  
![transition1](https://user-images.githubusercontent.com/6129601/71794677-38db7700-3008-11ea-9c4b-477e3840b11f.PNG)

Then the new screen is written (still inverted)
![transition2](https://user-images.githubusercontent.com/6129601/71794680-38db7700-3008-11ea-8dd7-ee9ee085edac.PNG)

Then the colors invert back to the way they should be.  
![screen2](https://user-images.githubusercontent.com/6129601/71794679-38db7700-3008-11ea-9b79-fd17656de81e.PNG)

This happens if I set the background to white & text to black, or background to black & text to white.  

Is this intentional?  Is there a way to avoid this?

**Comment by maclobdell** [comment]
I received helpful information that this behavior is expected.  It is due to the 4 stage screen update process.  
```
UpdateDisplay(CY_EINK_FULL_4STAGE, true)
```

I will try 2 stage and see if that looks okay.

**Comment by yeshwanthkt** [comment]
E-Ink works a little differently when compared to other displays, it inherently tends to hold on to its screen content. So updating an E-ink display is not straight forward, refer to the image below:
![eink-update-stages](https://user-images.githubusercontent.com/37586931/71874183-41869700-3147-11ea-8189-af652d5c3a6e.png)

There are 3 ways to update an E-ink display:

1) Four stage : In this method all 4 stages shown in the above image are performed to update the screen. The purpose of this four stage update is to reduce the ghost images which remain from the previous updates.
2) Two stage : In this method only Stage 1 and Stage 4 are performed to update the screen. This takes half the time of Four stage update method.
3) Partial update : In this method only Stage 4 is performed. This will leave ghost images on the screen from previous updates. 

In this example Four stage update is used by default. You can look for function calls:
```
UpdateDisplay(CY_EINK_FULL_4STAGE, true)
```

Instead of passing CY_EINK_FULL_4STAGE, you can pass CY_EINK_FULL_2STAGE or CY_EINK_PARTIAL during the function call. I would recommend using Two stage update to cut down refresh time by half and to get a fairly good screen update. You can also try Partial update as it works well for some examples.
